---@meta


---@class MapPinEnhanced
---@field modules table<string, table>
---@field GetModule fun(self, name:"Blizz"): Blizz
---@field GetModule fun(self, name:"Dialog"): Dialog
---@field GetModule fun(self, name:"EditorWindow"): EditorWindow
---@field GetModule fun(self, name:"Events"): Events
---@field GetModule fun(self, name:"Menu"): Menu
---@field GetModule fun(self, name:"Notify"): Notify
---@field GetModule fun(self, name:"Options"): Options
---@field GetModule fun(self, name:"PinFactory"): PinFactory
---@field GetModule fun(self, name:"PinProvider"): PinProvider
---@field GetModule fun(self, name:"Tracker"): Tracker
---@field GetModule fun(self, name:"SavedVars"): SavedVars
---@field GetModule fun(self, name:"SetFactory"): SetFactory
---@field GetModule fun(self, name:"SetManager"): SetManager
---@field GetModule fun(self, name:"SlashCommand"): SlashCommand
---@field GetModule fun(self, name:"Textures"): Textures
---@field GetModule fun(self, name:"Utils"): Utils
---@field GetModule fun(self, name:"PinSections"): PinSections
---@field GetModule fun(self, name:"PinTracking"): PinTracking
