name: Package Beta

on:
  push:
    tags:
      - "**-alpha**"
      - "**-beta**"
      
env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: BigWigsMods/packager@master
